script:
- |-
  git config user.name "epalto"
  git config user.email "epalanquestost@mgh.harvard.edu"
  git remote remove origin
  git remote add origin https://$GITHUB_API_KEY@github.com/mit-ccrg/icu-wiki.git > /dev/null 2>&1
  git remote add upstream https://$GITHUB_API_KEY@github.com/mit-ccrg/icu-wiki.git > /dev/null 2>&1
  git fetch origin
  git fetch upstream
  git merge upstream/master --no-edit
  git push origin HEAD:master > /dev/null 2>&1
  git push upstream HEAD:master > /dev/null 2>&1
env:
  matrix:
  - secure: pcjjAGoLa+ykDz63S7zvmYSCJn8EWC1e3ELVzeVo9JXTYacyA0D5JttWunzz30gq+vtc8TpVaMFFi+AXITCcAod6u4DbhJxFM+XL4l2U/L80axgF3qC+uM207VOGgwMXdyH8hJCLSlIn3OgoHvrY8l66hmuZY5EnKiT8ly0BKqllF2Zn+0femUSNcT6UyUjFglHPJdVpKqWca1y7E1y7o/YtEUtvJ2+hsvcpqeFp+blozxJL4wGu9sXZtT2CiN5Uq81POXurjKmVvFTttEz5wemCEtlY1JF5wuMOV7AiQz41Bi51a4Us0alrFa/y0dgZefrXj5j3qXedNDs4AW9JQVZvJ5hNBnIKXHKprfOZDVzJt8cM9SbatfJrb7RIMFgqW1K4ZNuwVbXIhSZv8/ExXIDW4XVNOyNjv7NqB/cMxF1Y9V99h1+pARZnW/vx5YP3F8kPQaFdtHIkgdywm0ETyux4Qo1JRK63UEA8m1k11Xxs03jKXQC5w7MgOG2CIc172cwUqbold8myr9PrsIoLgF7yAG7wPKAsL9+4B8G5EDzaDD4pbwHfXcz1IvtbUBuHBcMUTEyK5UopiZ8hh5t+J5BR//cmrV2OZkP49g3daCuCzpLMtMoTRsuQWIENUTkOZKMMIsuGP0L/YlWHQ0rRl62OPWA8kR5v4jRMalAEF0Y=
